# commit to be tagged for the new release
commit = "HEAD"

project_name = "sbc-raspberrypi5"
github_repo = "talos-rpi5/sbc-raspberrypi5"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

# previous = -
# pre_release = true

# [notes]
